// support-tips.js
// Support-specific quick-summary tips for synergy
// Massively expanded to cover all ADC_LIST champions and a wide variety of supports

const SUPPORT_TEMPLATES = {
  // ===========================================================================
  // I. ENGAGE SUPPORTS
  // ===========================================================================
  "Thresh": {
    synergy: {
      "Ashe": "Her slows (Passive/W) make it extremely easy to land your Hooks (Q). Her Arrow (R) is a perfect setup.",
      "Caitlyn": "Your Hook (Q) or Flay (E) places them on her Traps (W) for a long CC chain. Lantern (W) her out after she E's (Net).",
      "Jinx": "Your Q (Hook) sets up her E (Chompers) perfectly. You provide the peel she needs to scale.",
      "Ezreal": "Lantern (W) him in after he E's (Arcane Shift) out for aggressive repositioning. Your CC guarantees his W-Q (Essence Flux-Mystic Shot).",
      "Kai'Sa": "Your Q (Hook) gives her a free Plasma stack and an R (Killer Instinct) target. You are a high-kill-pressure lane.",
      "Miss Fortune": "Your Q (Hook) or R (The Box) holds them in place for her R (Bullet Time).",
      "Xayah": "Your Q (Hook) or E (Flay) groups them for her E (Bladecaller) root.",
      "Aphelios": "Ult (R) him with your Lantern (W) when he has White (Crescendum) for a high-damage dive combo.",
      "Tristana": "Your CC (Q, E) allows her to stack her E (Explosive Charge) for free. Lantern (W) her out after she W's (Rocket Jump) in.",
      "Sivir": "Your engage (Q) allows her to land a guaranteed double-hit Q (Boomerang Blade).",
      "Lucian": "Your Q (Hook) is a free full combo for him. Lantern (W) him in or out to enable his aggression.",
      "Samira": "Your E (Flay) and Q (Hook) are both knock-ups that stack her passive (Daredevil Impulse).",
      "Vayne": "Your E (Flay) can set up her E (Condemn) stun. You provide the peel she needs to survive lane.",
      "Draven": "Your CC (Q, E) guarantees he lands multiple axes. This is a high-kill-pressure lane. Play aggressively.",
      "Varus": "Your Q (Hook) or E (Flay) sets up his R (Chain of Corruption) for a permanent CC chain.",
      "Zeri": "Your peel (Q, E, R) is essential for her survival. Lantern (W) her over walls during her E (Spark Surge).",
      "Nilah": "Your hook (Q) pulls them in for her Q (Formless Blade). Your Lantern (W) is a safe 'engage' for her.",
      "Smolder": "You provide the best peel. Your job is to keep him safe so he can stack. Use Lantern (W) to save him from ganks.",
      "Twitch": "Your hook (Q) into his W (Venom Cask) and E (Contaminate) is a huge burst combo.",
      "Kog'Maw": "You keep him safe. Your E (Flay) pushes divers away, and your W (Lantern) is his only escape.",
      "Kalista": "Your perfect partner. She can ult (R) you in for a guaranteed Flay (E) or Hook (Q) engage.",
      "Senna": "Your Q (Hook) sets up her W (Last Embrace) root. You can Lantern (W) her for aggressive soul collecting.",
      "Seraphine": "Your Q (Hook) guarantees her E (Beat Drop) stun and full Q (High Note) damage.",
      "Veigar": "Your Q (Hook) or E (Flay) can pull or push enemies *into* his E (Event Horizon) stun.",
      "Ziggs": "Your Q (Hook) sets up his E (Hexplosive Minefield) and W (Satchel Charge) combo.",
      "Karthus": "Your Q (Hook) holds them in his E (Defile). Your R (The Box) slow is devastating with his Q (Lay Waste).",
      "Swain": "Your Q (Hook) or E (Flay) guarantees his E (Nevermove) root. This is a double-pull lane.",
      "Heimerdinger": "Your Q (Hook) pulls them into his turrets (Q). Your peel (E) protects his nest."
    }
  },
  "Leona": {
    synergy: {
      "Ashe": "Your E (Zenith Blade) engage allows her to kite and slow (Passive) them permanently.",
      "Caitlyn": "Your stun (Q) guarantees her trap (W) root. A classic CC chain.",
      "Jinx": "Your E (Zenith Blade) sets up her E (Chompers). Your R (Solar Flare) is a perfect follow-up.",
      "Ezreal": "He can E (Arcane Shift) to follow up your E (Zenith Blade) from a safe distance.",
      "Kai'Sa": "Your passive (Sunlight) procs on her Q (Icathian Rain). Your all-in gives her free R (Killer Instinct) engage.",
      "Miss Fortune": "Your full combo (E-Q-R) holds them in place for her full R (Bullet Time). A devastating level 6 all-in.",
      "Xayah": "Your engage holds them down, allowing her to set up a field of feathers (E) for a massive root.",
      "Aphelios": "Your engage with Purple (Gravitum) Q (Binding) is a 3-second root. A guaranteed kill.",
      "Tristana": "Her W (Rocket Jump) follow-up to your E (Zenith Blade) is unmatched. All-in on cooldown.",
      "Sivir": "You provide the engage she lacks. Your R (Solar Flare) allows her to run them down with her R (On The Hunt).",
      "Lucian": "His passive (Lightslinger) procs your passive (Sunlight) instantly. Look for all-ins at level 2/3.",
      "Samira": "Your E (Zenith Blade) and Q (Shield of Daybreak) stack her passive (Daredevil Impulse) and set up her R (Inferno Trigger).",
      "Vayne": "You provide the lockdown. Your E (Zenith Blade) into her E (Condemn) is a guaranteed stun.",
      "Draven": "Your E (Zenith Blade) and Q (Shield of Daybreak) is a free kill for him. All-in at level 2.",
      "Varus": "Your R (Solar Flare) into his R (Chain of Corruption) is a teamfight-winning CC chain.",
      "Zeri": "You provide the frontline she needs. Your R (Solar Flare) is the engage she needs to follow up with her R (Lightning Crash).",
      "Nilah": "Your all-in (E-Q) allows her to E-Q-R for a massive combo.",
      "Smolder": "You provide peel, but he wants to farm. Only engage (E) if the kill is 100% free.",
      "Twitch": "Your R (Solar Flare) is the perfect setup for his R (Spray and Pray) from stealth (Q).",
      "Kog'Maw": "You provide peel. Your Q (Shield of Daybreak) stun is a great disengage tool.",
      "Kalista": "Your E (Zenith Blade) engage is strong. She can R (Fate's Call) you for a secondary engage or disengage.",
      "Senna": "Your E (Zenith Blade) sets up her W (Last Embrace) root. A very long CC chain.",
      "Seraphine": "Your R (Solar Flare) is a massive setup for her R (Encore).",
      "Veigar": "Your E (Zenith Blade) and Q (Shield of Daybreak) guarantee his E (Event Horizon) stun.",
      "Ziggs": "Your engage (E-Q) holds them in his E (Hexplosive Minefield) and R (Mega Inferno Bomb).",
      "Karthus": "Your E-Q-R (Full Combo) holds them in his E (Defile) and guarantees his Q (Lay Waste) hits.",
      "Swain": "Your E (Zenith Blade) guarantees his E (Nevermove). This is a terrifying all-in lane.",
      "Heimerdinger": "Your E-Q (Engage) holds them inside his turrets (Q) and sets up his E (Grenade) stun."
    }
  },
  "Nautilus": {
    synergy: {
      "Ashe": "Your Q (Hook) or R (Depth Charge) is a free R (Arrow) for her. A global CC chain.",
      "Caitlyn": "Your Q (Hook) is a free W (Trap). A classic CC chain.",
      "Jinx": "Your Q (Hook) into her E (Chompers) is a guaranteed root chain.",
      "Ezreal": "Your CC (Q, R, Passive) guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your hook (Q) or ult (R) gives her a free plasma stack and an R (Killer Instinct) target. All-in lane.",
      "Miss Fortune": "Your R (Depth Charge) and Q (Hook) lock them down for her R (Bullet Time).",
      "Xayah": "Your all-in (Q, R) holds them in place for her E (Bladecaller) root.",
      "Aphelios": "Your CC (Q, R) is the peel he needs. Your engage with his Purple (Gravitum) weapon is a kill.",
      "Tristana": "Your Q (Hook) allows her to W (Rocket Jump) in and stack her E (Explosive Charge).",
      "Sivir": "You provide the engage she lacks. Your R (Depth Charge) guarantees her Q (Boomerang Blade).",
      "Lucian": "Your Q (Hook) and Passive (Staggering Blow) is a free full combo (E-Q-W) for him.",
      "Samira": "Your full CC chain (Q, Passive, E, R) allows you to get her full S-rank combo (R) for free.",
      "Vayne": "Your Q (Hook) or R (Depth Charge) can set up her E (Condemn) stun.",
      "Draven": "Your Q (Hook) is a free kill for him. All-in at level 2.",
      "Varus": "Your R (Depth Charge) into his R (Chain of Corruption) is a teamfight-winning CC chain.",
      "Zeri": "You provide the frontline and peel. Your R (Depth Charge) is the setup she needs.",
      "Nilah": "Your Q (Hook) pulls them in for her E-Q-R (Full Combo).",
      "Smolder": "Your job is peel. Use Q (Hook), E (Riptide), and R (Depth Charge) to keep enemies *away* from him.",
      "Twitch": "Your R (Depth Charge) is a great setup for his Q (Ambush) all-in.",
      "Kog'Maw": "Your job is peel. You are a walking wall of CC to keep him safe.",
      "Kalista": "Your Q (Hook) engage is strong. She can R (Fate's Call) you for a secondary engage.",
      "Senna": "Your Q (Hook) or R (Depth Charge) is a perfect setup for her W (Last Embrace) root.",
      "Seraphine": "Your R (Depth Charge) knock-up guarantees her R (Encore) charm.",
      "Veigar": "Your Q (Hook) or R (Depth Charge) is a free E (Event Horizon) stun.",
      "Ziggs": "Your Q (Hook) or R (Depth Charge) holds them in his E (Hexplosive Minefield) and R (Mega Inferno Bomb).",
      "Karthus": "Your full CC chain (Q, R, E, Passive) holds them in his E (Defile) for massive damage.",
      "Swain": "Your Q (Hook) into his E (Nevermove) is a deadly double-pull combo.",
      "Heimerdinger": "Your Q (Hook) pulls them into his turrets (Q). Your R (Depth Charge) sets up his R-E (Upgraded Grenade) stun."
    }
  },
  "Alistar": {
    synergy: {
      "Ashe": "Your W-Q (Headbutt-Pulverize) combo allows her to kite them down with slows (Passive).",
      "Caitlyn": "Your W-Q (Headbutt-Pulverize) is a free W (Trap) for her. You can also W (Headbutt) them *into* traps.",
      "Jinx": "Your W-Q (Headbutt-Pulverize) combo is a perfect setup for her E (Chompers).",
      "Ezreal": "Your W-Q (Headbutt-Pulverize) combo guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your W-Q (Headbutt-Pulverize) is a free plasma (Passive) stack and R (Killer Instinct) setup.",
      "Miss Fortune": "Your W-Q (Headbutt-Pulverize) combo holds them in place for her E (Make It Rain) and R (Bullet Time).",
      "Xayah": "Your W-Q (Headbutt-Pulverize) combo holds them for her E (Bladecaller) root.",
      "Aphelios": "Your W-Q (Headbutt-Pulverize) combo is the peel he needs. Your R (Unbreakable Will) lets you tank forever.",
      "Tristana": "Your W-Q (Headbutt-Pulverize) combo is a free E (Explosive Charge) stack for her.",
      "Sivir": "You provide the engage. Your W-Q (Headbutt-Pulverize) combo allows her to land a double Q (Boomerang Blade).",
      "Lucian": "Your W-Q (Headbutt-Pulverize) combo is a free all-in for him.",
      "Samira": "Your W-Q (Headbutt-Pulverize) combo is a knock-up that stacks her passive (Daredevil Impulse). Perfect all-in.",
      "Vayne": "Your W-Q (Headbutt-Pulverize) combo can set up her E (Condemn) stun. You are her best peel.",
      "Draven": "Your W-Q (Headbutt-Pulverize) combo is a free kill for him. All-in at level 2.",
      "Varus": "Your W-Q (Headbutt-Pulverize) combo sets up his R (Chain of Corruption).",
      "Zeri": "Your peel (W, Q) is essential for her. You can W-Q (Headbutt-Pulverize) divers off of her.",
      "Nilah": "Your W-Q (Headbutt-Pulverize) combo is the perfect setup for her E-Q-R (Full Combo).",
      "Smolder": "You are a peel-bot. Your W (Headbutt) and Q (Pulverize) keep him safe.",
      "Twitch": "Your W-Q (Headbutt-Pulverize) combo is a great setup for his all-in.",
      "Kog'Maw": "You are his personal bodyguard. W (Headbutt) and Q (Pulverize) any divers.",
      "Kalista": "Your W-Q (Headbutt-Pulverize) combo is strong. Her R (Fate's Call) on you is a game-changing engage.",
      "Senna": "Your W-Q (Headbutt-Pulverize) combo sets up her W (Last Embrace) root.",
      "Seraphine": "Your W-Q (Headbutt-Pulverize) combo guarantees her E (Beat Drop) stun.",
      "Veigar": "Your W-Q (Headbutt-Pulverize) combo is a free E (Event Horizon) stun.",
      "Ziggs": "Your W-Q (Headbutt-Pulverize) combo holds them in his E (Hexplosive Minefield).",
      "Karthus": "Your W-Q (Headbutt-Pulverize) combo holds them in his E (Defile).",
      "Swain": "Your W-Q (Headbutt-Pulverize) combo is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your W-Q (Headbutt-Pulverize) combo holds them in his turrets (Q). You are the bouncer for his nest."
    }
  },
  "Blitzcrank": {
    synergy: {
      "Ashe": "Your Q (Rocket Grab) is a free R (Arrow). A hook is a guaranteed kill.",
      "Caitlyn": "Your Q (Rocket Grab) into her W (Trap) is the oldest and most deadly combo in bot lane.",
      "Jinx": "Your Q (Rocket Grab) into her E (Chompers) is a perma-CC. A hook is a kill.",
      "Ezreal": "Your Q (Rocket Grab) guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your Q (Rocket Grab) is a free plasma (Passive) stack.",
      "Miss Fortune": "Your Q (Rocket Grab) and R (Static Field) silence holds them in place for her R (Bullet Time).",
      "Xayah": "Your Q (Rocket Grab) pulls them through her feathers (E) for an easy root.",
      "Aphelios": "Your Q (Rocket Grab) with his Purple (Gravitum) root is a long CC chain.",
      "Tristana": "Your Q (Rocket Grab) is a free E (Explosive Charge) stack for her.",
      "Sivir": "Anti-synergy. She will E (Spell Shield) your Q (Rocket Grab) for free mana. Do not pick together.",
      "Lucian": "Your Q (Rocket Grab) is a free all-in for him.",
      "Samira": "Your Q (Rocket Grab) and E (Power Fist) are knock-ups that stack her passive (Daredevil Impulse).",
      "Vayne": "Your Q (Rocket Grab) can pull them into a wall for her E (Condemn) stun.",
      "Draven": "Your Q (Rocket Grab) is a free kill. All-in at level 1.",
      "Varus": "Your Q (Rocket Grab) sets up his R (Chain of Corruption).",
      "Zeri": "Your Q (Rocket Grab) is one of the few ways to lock her down.",
      "Nilah": "Your Q (Rocket Grab) pulls them in for her E-Q (Full Combo).",
      "Smolder": "You provide peel. Your E (Power Fist) and R (Static Field) keep him safe. Only Q (Rocket Grab) defensively.",
      "Twitch": "Your Q (Rocket Grab) into his W (Venom Cask) and E (Contaminate) is a huge burst combo.",
      "Kog'Maw": "Your Q (Rocket Grab) is good peel. Your E (Power Fist) and R (Static Field) stop divers.",
      "Kalista": "Your Q (Rocket Grab) is a good setup for her E (Rend) stack.",
      "Senna": "Your Q (Rocket Grab) sets up her W (Last Embrace) root.",
      "Seraphine": "Your Q (Rocket Grab) guarantees her E (Beat Drop) stun.",
      "Veigar": "Your Q (Rocket Grab) into his E (Event Horizon) is a free kill.",
      "Ziggs": "Your Q (Rocket Grab) pulls them into his E (Hexplosive Minefield).",
      "Karthus": "Your Q (Rocket Grab) pulls them into his E (Defile). A hook is a kill.",
      "Swain": "Your Q (Rocket Grab) into his E (Nevermove) is a deadly double-pull combo.",
      "Heimerdinger": "Your Q (Rocket Grab) pulls them into his turret (Q) nest. A free kill."
    }
  },
  "Rell": {
    synergy: {
      "Ashe": "Your W (Ferromancy: Crash Down) and R (Magnet Storm) group them for her W (Volley) and R (Arrow).",
      "Caitlyn": "Your W (Crash Down) knock-up is a free W (Trap) for her.",
      "Jinx": "Your W (Crash Down) and R (Magnet Storm) group them for her R (Super Mega Death Rocket!) and E (Chompers).",
      "Ezreal": "Your W (Crash Down) guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your W (Crash Down) is a free plasma (Passive) stack and R (Killer Instinct) setup.",
      "Miss Fortune": "Your R (Magnet Storm) pulls them all together for her R (Bullet Time). A devastating combo.",
      "Xayah": "Your R (Magnet Storm) pulls them all through her feathers (E) for a massive root.",
      "Aphelios": "Your W (Crash Down) and R (Magnet Storm) are perfect setup for his R (Moonlight Vigil) with Red (Infernum).",
      "Tristana": "Your W (Crash Down) is a free E (Explosive Charge) stack for her.",
      "Sivir": "You provide the engage she lacks. Your R (Magnet Storm) groups them for her Q (Boomerang Blade) and W (Ricochet).",
      "Lucian": "Your W (Crash Down) is a free all-in for him.",
      "Samira": "Your R (Magnet Storm) and W (Crash Down) stack her passive (Daredevil Impulse) and group enemies for her R (Inferno Trigger).",
      "Vayne": "Your W (Crash Down) can set up her E (Condemn) stun. Your E (Attract and Repel) stun is great peel.",
      "Draven": "Your W (Crash Down) is a free kill for him.",
      "Varus": "Your R (Magnet Storm) into his R (Chain of Corruption) is a teamfight-winning CC chain.",
      "Zeri": "You provide the frontline. Your W (Crash Down) and R (Magnet Storm) are the setup she needs.",
      "Nilah": "Your R (Magnet Storm) pulls them in for her R (Apotheosis). A perfect wombo-combo.",
      "Smolder": "You provide peel. Your W (Crash Down) and E (Attract and Repel) keep him safe.",
      "Twitch": "Your R (Magnet Storm) groups them perfectly for his R (Spray and Pray).",
      "Kog'Maw": "You provide peel. Your W (Crash Down) and E (Attract and Repel) keep divers off him.",
      "Kalista": "Your W (Crash Down) is a good setup. Her R (Fate's Call) on you is a massive engage.",
      "Senna": "Your W (Crash Down) sets up her W (Last Embrace) root.",
      "Seraphine": "Your R (Magnet Storm) pulls them together for her R (Encore).",
      "Veigar": "Your W (Crash Down) or E (Attract and Repel) stun is a free E (Event Horizon) stun.",
      "Ziggs": "Your R (Magnet Storm) groups them for his R (Mega Inferno Bomb).",
      "Karthus": "Your R (Magnet Storm) holds them in his E (Defile).",
      "Swain": "Your W (Crash Down) and R (Magnet Storm) are a perfect setup for his R (Demonic Ascension) and E (Nevermove).",
      "Heimerdinger": "Your W (Crash Down) and R (Magnet Storm) hold them in his turret (Q) nest."
    }
  },
  "Rakan": {
    synergy: {
      "Ashe": "Your W (Grand Entrance) is a free R (Arrow) for her. Your E (Battle Dance) shields let her kite.",
      "Caitlyn": "Your W (Grand Entrance) is a free W (Trap) for her.",
      "Jinx": "Your W (Grand Entrance) sets up her E (Chompers).",
      "Ezreal": "Your W (Grand Entrance) guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your W (Grand Entrance) is a free plasma (Passive) stack and R (Killer Instinct) setup.",
      "Miss Fortune": "Your W (Grand Entrance) and R (The Quickness) group and charm them for her R (Bullet Time).",
      "Xayah": "Your perfect partner. Your W (Grand Entrance) sets up her E (Bladecaller). Your E (Battle Dance) has double range on her.",
      "Aphelios": "Your W (Grand Entrance) and R (The Quickness) are the engage and peel he needs.",
      "Tristana": "Your W (Grand Entrance) is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your W (Grand Entrance) and R (The Quickness) are the engage she needs for her R (On The Hunt).",
      "Lucian": "Your W (Grand Entrance) is a free all-in for him.",
      "Samira": "Your W (Grand Entrance) and R (The Quickness) stack her passive (Daredevil Impulse) and set up her R (Inferno Trigger).",
      "Vayne": "Your W (Grand Entrance) can set up her E (Condemn) stun. Your peel (E, W) is very strong.",
      "Draven": "Your W (Grand Entrance) is a free kill for him.",
      "Varus": "Your W (Grand Entrance) and R (The Quickness) set up his R (Chain of Corruption).",
      "Zeri": "Your W (Grand Entrance) and R (The Quickness) are the engage she needs.",
      "Nilah": "Your W (Grand Entrance) knock-up allows her to E-Q-R for a massive wombo-combo. Her passive (Joy Unending) amps your E (Battle Dance).",
      "Smolder": "You provide good peel (W, R) and mobility (E) to keep him safe.",
      "Twitch": "Your W (Grand Entrance) and R (The Quickness) are a great setup for his R (Spray and Pray).",
      "Kog'Maw": "Your peel (W, E, R) is excellent for keeping him alive.",
      "Kalista": "Her R (Fate's Call) on you is a massive, long-range engage.",
      "Senna": "Your W (Grand Entrance) sets up her W (Last Embrace) root.",
      "Seraphine": "Your W (Grand Entrance) and R (The Quickness) are a perfect setup for her R (Encore).",
      "Veigar": "Your W (Grand Entrance) is a free E (Event Horizon) stun.",
      "Ziggs": "Your W (Grand Entrance) and R (The Quickness) hold them in his E (Hexplosive Minefield).",
      "Karthus": "Your W (Grand Entrance) and R (The Quickness) hold them in his E (Defile).",
      "Swain": "Your W (Grand Entrance) is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your W (Grand Entrance) and R (The Quickness) hold them in his turret (Q) nest."
    }
  },
  
  // ===========================================================================
  // II. ENCHANTER SUPPORTS
  // ===========================================================================
  "Lulu": {
    synergy: {
      "Ashe": "Your E (Help, Pix!) shield and W (Whimsy) speed make her an unkillable kiting machine.",
      "Caitlyn": "Your W (Whimsy) on her gives her the speed to position for traps (W). Your R (Wild Growth) saves her from divers.",
      "Jinx": "Your W (Whimsy) on her during her passive (Get Excited!) makes her unstoppable.",
      "Ezreal": "Your E (Help, Pix!) on him gives his Q (Mystic Shot) extra poke. Your W (Polymorph) on an enemy guarantees his combo.",
      "Kai'Sa": "Your R (Wild Growth) on her when she R's (Killer Instinct) in is a classic dive combo.",
      "Miss Fortune": "Your W (Whimsy) gives her the speed to position for a perfect R (Bullet Time).",
      "Xayah": "Your E (Help, Pix!) and R (Wild Growth) provide the peel she needs to set up feathers (E).",
      "Aphelios": "You are his personal bodyguard. Your W (Whimsy), E (Help, Pix!), and R (Wild Growth) keep him alive to scale.",
      "Tristana": "Your E (Help, Pix!) and R (Wild Growth) on her when she W's (Rocket Jump) in makes her an unkillable assassin.",
      "Sivir": "Your W (Whimsy) on her, combined with her R (On The Hunt), makes your team a high-speed death ball.",
      "Lucian": "Your E (Help, Pix!) gives his passive (Lightslinger) extra damage. Your W (Polymorph) guarantees his all-in.",
      "Samira": "Your R (Wild Growth) on her when she R's (Inferno Trigger) in a fight is devastating.",
      "Vayne": "Your best friend. Her shield (E), polymorph (W), and ult (R) give you the time you need to scale and shred targets.",
      "Draven": "Your W (Whimsy) gives him speed to catch axes. Your W (Polymorph) on an enemy is a free kill.",
      "Varus": "Your W (Whimsy) on him (On-Hit build) makes him a kiting god. Your peel (W, R) keeps him safe.",
      "Zeri": "Your 'tempo' and scaling partner. Her W (Whimsy) makes her uncatchable, and her E (Help, Pix!) gives her Q (Burst Fire) extra damage.",
      "Nilah": "Your R (Wild Growth) on her when she R's (Apotheosis) in is a wombo-combo. Her passive (Joy Unending) amplifies your shields.",
      "Smolder": "You provide excellent peel (W, R) to help him stack safely.",
      "Twitch": "Your W (Whimsy) and R (Wild Growth) turn him into a 1v5 hyper-carry during his R (Spray and Pray).",
      "Kog'Maw": "The classic 'Jugger-Maw'. Your entire kit is designed to keep you alive while you melt the enemy team.",
      "Kalista": "Your W (Whimsy) on her makes her kiting (Passive) insane. Her R (Fate's Call) can save you.",
      "Senna": "Your E (Help, Pix!) on her gives her Q (Piercing Darkness) and autos more poke.",
      "Seraphine": "Your peel (W, R) keeps her safe to poke. Your E (Help, Pix!) helps her land E (Beat Drop).",
      "Veigar": "Your W (Polymorph) and R (Wild Growth) are perfect peel to let him scale.",
      "Ziggs": "Your peel (W, R) keeps him safe to siege. Your E (Help, Pix!) gives his auto-attacks (Passive) more poke.",
      "Karthus": "Your W (Polymorph) and R (Wild Growth) can keep him alive to use his R (Requiem).",
      "Swain": "Your W (Whimsy) gives him the speed to land E (Nevermove). Your R (Wild Growth) on him during his R (Demonic Ascension) makes him a raid boss.",
      "Heimerdinger": "Your W (Polymorph) and R (Wild Growth) are perfect peel for his turret (Q) nest."
    }
  },
  "Janna": {
    synergy: {
      "Ashe": "Your E (Eye of the Storm) shield gives her AD, making her W (Volley) poke stronger. Your Q (Howling Gale) and R (Monsoon) are perfect disengage.",
      "Caitlyn": "Your E (Eye of the Storm) AD shield makes her headshots hit even harder.",
      "Jinx": "Your Q (Howling Gale) and R (Monsoon) are the peel she needs to get resets (Passive).",
      "Ezreal": "Your E (Eye of the Storm) AD shield buffs his Q (Mystic Shot) poke.",
      "Kai'Sa": "You provide the disengage she needs to survive early. Your R (Monsoon) can reset a bad fight.",
      "Miss Fortune": "Your R (Monsoon) is anti-synergy with her R (Bullet Time). Be careful not to push them out.",
      "Xayah": "Your E (Eye of the Storm) shield and peel (Q, R) let her set up feathers (E) safely.",
      "Aphelios": "You are a peel-bot. Your job is to keep him alive. Your Q (Howling Gale) and R (Monsoon) stop all divers.",
      "Tristana": "Anti-synergy. Your Q (Howling Gale) and R (Monsoon) push enemies *out* of her E (Explosive Charge) bomb.",
      "Sivir": "Your W (Zephyr) slow and Q (Howling Gale) help her land Q (Boomerang Blade).",
      "Lucian": "Your E (Eye of the Storm) shield gives his all-in (E-Q-W) more damage.",
      "Samira": "Anti-synergy. You push enemies away, she wants to dive in. Do not pick together.",
      "Vayne": "Perfect peel. Your Q (Howling Gale) and R (Monsoon) let her scale for free.",
      "Draven": "Your E (Eye of the Storm) shield gives him more AD for his axes. Your Q (Howling Gale) can set up kills.",
      "Varus": "Your peel (Q, R) keeps him safe to poke (Lethality build) or auto (On-Hit build).",
      "Zeri": "Your peel (Q, R) and her E (Spark Surge) make her uncatchable.",
      "Nilah": "Her passive (Joy Unending) amplifies your E (Eye of the Storm) shield. Your R (Monsoon) can separate enemies for her.",
      "Smolder": "The ultimate peel support. She ensures no one ever touches you, allowing you to get 225 stacks.",
      "Twitch": "Your peel (Q, R) keeps him safe to stack E (Contaminate).",
      "Kog'Maw": "Her peel (Q, R) is god-tier. She keeps assassins off you.",
      "Kalista": "Her R (Fate's Call) can pull you in to use a perfect R (Monsoon) or Q (Howling Gale).",
      "Senna": "Your E (Eye of the Storm) shield on her makes her Q (Piercing Darkness) poke even stronger.",
      "Seraphine": "Your Q (Howling Gale) is a great setup for her R (Encore). You keep her safe.",
      "Veigar": "You provide the peel he needs to stack. Your Q (Howling Gale) can knock enemies *into* his E (Event Horizon).",
      "Ziggs": "You provide the peel he needs to siege. Your E (Eye of the Storm) shield buffs his auto (Passive) tower damage.",
      "Karthus": "Your peel (Q, R) keeps him alive. Your R (Monsoon) can push enemies *into* his E (Defile).",
      "Swain": "Your Q (Howling Gale) can set up his E (Nevermove). Your R (Monsoon) can peel for him or split the enemy team.",
      "Heimerdinger": "You are the perfect bodyguard for his turret (Q) nest. Your Q (Howling Gale) and R (Monsoon) stop all divers."
    }
  },
  "Nami": {
    synergy: {
      "Ashe": "Your E (Tidecaller's Blessing) slow stacks with her slow (Passive). They can't move.",
      "Caitlyn": "Your Q (Aqua Prison) bubble is a free W (Trap) for her. Your E (Tidecaller's Blessing) buffs her headshots.",
      "Jinx": "Your Q (Aqua Prison) sets up her E (Chompers). Your W (Ebb and Flow) provides good sustain.",
      "Ezreal": "Your E (Tidecaller's Blessing) on his Q (Mystic Shot) is strong poke. Your Q (Aqua Prison) guarantees his combo.",
      "Kai'Sa": "Your E (Tidecaller's Blessing) helps her stack plasma (Passive). Your Q (Aqua Prison) is a good setup.",
      "Miss Fortune": "Your R (Tidal Wave) into her R (Bullet Time) is a classic wombo-combo.",
      "Xayah": "Your Q (Aqua Prison) bubble holds them for her E (Bladecaller) root.",
      "Aphelios": "Your W (Ebb and Flow) sustain helps him survive laning. Your Q (Aqua Prison) is great peel.",
      "Tristana": "Your Q (Aqua Prison) bubble is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your E (Tidecaller's Blessing) makes her W (Ricochet) bounce with a slow. Very strong.",
      "Lucian": "Her E (Tidecaller's Blessing) procs on both hits of his passive (Lightslinger), giving massive burst and speed.",
      "Samira": "Your Q (Aqua Prison) and R (Tidal Wave) are knock-ups that stack her passive (Daredevil Impulse).",
      "Vayne": "Your E (Tidecaller's Blessing) on her helps her kite. Your Q (Aqua Prison) can set up her E (Condemn) stun.",
      "Draven": "Her E (Tidecaller's Blessing) slow makes it easy for him to land axes. Your heal (W) sustains his aggression.",
      "Varus": "Your R (Tidal Wave) into his R (Chain of Corruption) is a devastating combo.",
      "Zeri": "Your E (Tidecaller's Blessing) on her Q (Burst Fire) is strong poke. Your R (Tidal Wave) is great engage.",
      "Nilah": "Your Q (Aqua Prison) and R (Tidal Wave) are great setups for her all-in. Her passive (Joy Unending) amps your W (Ebb and Flow).",
      "Smolder": "Your W (Ebb and Flow) sustain is perfect for his stacking lane. Your Q (Aqua Prison) is great peel.",
      "Twitch": "Your E (Tidecaller's Blessing) on his R (Spray and Pray) is very strong. Your Q (Aqua Prison) is good setup.",
      "Kog'Maw": "Your W (Ebb and Flow) sustain keeps him healthy. Your Q (Aqua Prison) and R (Tidal Wave) are great peel.",
      "Kalista": "Your E (Tidecaller's Blessing) on her makes her spears (Passive) slow. Very oppressive.",
      "Senna": "Your E (Tidecaller's Blessing) on her Q (Piercing Darkness) is strong poke. Your Q (Aqua Prison) sets up her W (Last Embrace).",
      "Seraphine": "Your R (Tidal Wave) into her R (Encore) is a full-team CC chain.",
      "Veigar": "Your Q (Aqua Prison) bubble is a free E (Event Horizon) stun.",
      "Ziggs": "Your Q (Aqua Prison) bubble sets up his full combo (E-W-Q).",
      "Karthus": "Your Q (Aqua Prison) and R (Tidal Wave) hold them in his E (Defile).",
      "Swain": "Your Q (Aqua Prison) bubble is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your Q (Aqua Prison) bubble holds them in his turrets (Q) and sets up his E (Grenade) stun."
    }
  },
  "Soraka": {
    synergy: {
      "Ashe": "Your E (Equinox) silence/root sets up her R (Arrow). Your W (Astral Infusion) keeps her healthy to kite.",
      "Caitlyn": "Your W (Astral Infusion) and R (Wish) keep her healthy to poke. Your E (Equinox) stops divers.",
      "Jinx": "Your W (Astral Infusion) and R (Wish) keep her healthy to scale. Your E (Equinox) is perfect peel.",
      "Ezreal": "Your W (Astral Infusion) keeps him healthy. Your E (Equinox) stops divers from jumping on him.",
      "Kai'Sa": "Your W (Astral Infusion) and R (Wish) provide massive healing when she R's (Killer Instinct) in.",
      "Miss Fortune": "Your E (Equinox) root is a good setup for her R (Bullet Time).",
      "Xayah": "Your E (Equinox) and R (Wish) are perfect peel for her.",
      "Aphelios": "Your W (Astral Infusion) and R (Wish) are the sustain he needs to survive lane.",
      "Tristana": "Your W (Astral Infusion) and R (Wish) heal her when she W's (Rocket Jump) in.",
      "Sivir": "Your W (Astral Infusion) and R (Wish) keep her healthy to perma-push.",
      "Lucian": "Your E (Equinox) root is a good setup for his all-in.",
      "Samira": "Your E (Equinox) can silence and root enemies in her R (Inferno Trigger).",
      "Vayne": "Your W (Astral Infusion) and R (Wish) keep her healthy to scale. Your E (Equinox) stops divers.",
      "Draven": "Your W (Astral Infusion) fuels his aggression. Your E (Equinox) is a free kill setup.",
      "Varus": "Your E (Equinox) root sets up his R (Chain of Corruption).",
      "Zeri": "Your W (Astral Infusion) and R (Wish) keep her healthy. Your E (Equinox) stops divers.",
      "Nilah": "Her passive (Joy Unending) amplifies your W (Astral Infusion) and R (Wish). A massive heal/shield lane.",
      "Smolder": "Your W (Astral Infusion) and R (Wish) are the sustain he needs to stack safely.",
      "Twitch": "Your W (Astral Infusion) and R (Wish) keep him healthy for his all-in.",
      "Kog'Maw": "Your W (Astral Infusion) and R (Wish) are the infinite health he needs to melt teams.",
      "Kalista": "Your W (Astral Infusion) keeps her healthy. Her R (Fate's Call) can save you.",
      "Senna": "Your E (Equinox) root sets up her W (Last Embrace) root.",
      "Seraphine": "Your E (Equinox) root sets up her E (Beat Drop) stun. You are a massive sustain lane.",
      "Veigar": "Your E (Equinox) root is a free E (Event Horizon) stun.",
      "Ziggs": "Your W (Astral Infusion) and R (Wish) keep him healthy to poke.",
      "Karthus": "Your E (Equinox) root holds them in his E (Defile). Your R (Wish) counters the enemy Karthus R (Requiem).",
      "Swain": "Your E (Equinox) root sets up his E (Nevermove). Your W (Astral Infusion) keeps him healthy in his R (Demonic Ascension).",
      "Heimerdinger": "Your E (Equinox) stops divers from killing his turrets (Q)."
    }
  },
  "Sona": {
    synergy: {
      "Ashe": "Your E (Song of Celerity) speed and her slows (Passive) make an uncatchable kiting lane. Your R (Crescendo) sets up her R (Arrow).",
      "Caitlyn": "Your R (Crescendo) stun is a free W (Trap) for her. Your W (Aria of Perseverance) provides sustain.",
      "Jinx": "Your sustain (W) and speed (E) help her scale. Your R (Crescendo) is great setup/peel.",
      "Ezreal": "Your Q (Hymn of Valor) poke and his Q (Mystic Shot) poke are very oppressive.",
      "Kai'Sa": "Your R (Crescendo) stun is a free plasma (Passive) stack.",
      "Miss Fortune": "Your R (Crescendo) stun into her R (Bullet Time) is a classic wombo-combo.",
      "Xayah": "Your R (Crescendo) stun holds them for her E (Bladecaller) root.",
      "Aphelios": "Your W (Aria of Perseverance) sustain helps him scale. Your R (Crescendo) is perfect peel.",
      "Tristana": "Your R (Crescendo) stun is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your E (Song of Celerity) speed and her R (On The Hunt) make a 'Gotta Go Fast' combo.",
      "Lucian": "Your Q (Hymn of Valor) poke enables his all-in.",
      "Samira": "Your R (Crescendo) stun is a good setup for her all-in.",
      "Vayne": "Your W (Aria of Perseverance) sustain helps her scale. Your R (Crescendo) is great peel.",
      "Draven": "Your W (Aria of Perseverance) sustain fuels his aggression. Your R (Crescendo) is a free kill.",
      "Varus": "Your R (Crescendo) stun into his R (Chain of Corruption) is a devastating CC chain.",
      "Zeri": "Your E (Song of Celerity) speed and R (Crescendo) are perfect for her R (Lightning Crash) all-in.",
      "Nilah": "Her passive (Joy Unending) amplifies your W (Aria of Perseverance) shield/heal. Your R (Crescendo) sets up her R (Apotheosis).",
      "Smolder": "Your W (Aria of Perseverance) sustain is perfect for his stacking lane.",
      "Twitch": "Your R (Crescendo) stun is a great setup for his R (Spray and Pray).",
      "Kog'Maw": "Your W (Aria of Perseverance) sustain and R (Crescendo) peel are perfect for him.",
      "Kalista": "Your R (Crescendo) is good setup. Her R (Fate's Call) can save you.",
      "Senna": "Your Q (Hymn of Valor) poke and her Q (Piercing Darkness) poke are very strong. Your R (Crescendo) sets up her W (Last Embrace).",
      "Seraphine": "The ultimate poke/sustain lane. Your R (Crescendo) into her R (Encore) is a full-team CC chain.",
      "Veigar": "Your R (Crescendo) stun is a free E (Event Horizon) stun.",
      "Ziggs": "Your Q (Hymn of Valor) poke and his Q (Bouncing Bomb) poke are very oppressive.",
      "Karthus": "Your R (Crescendo) stun holds them in his E (Defile).",
      "Swain": "Your R (Crescendo) stun is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your R (Crescendo) stun holds them in his turret (Q) nest."
    }
  },
  "Milio": {
    synergy: {
      "Ashe": "Your W (Cozy Campfire) gives her bonus range to kite. Your R (Breath of Life) is perfect peel.",
      "Caitlyn": "Your W (Cozy Campfire) gives her even more range, making her poke unbearable for the enemy.",
      "Jinx": "Your W (Cozy Campfire) range and R (Breath of Life) peel help her scale safely.",
      "Ezreal": "Your W (Cozy Campfire) gives his Q (Mystic Shot) more range. Your R (Breath of Life) cleanses CC.",
      "Kai'Sa": "Your R (Breath of Life) cleanse is perfect for when she R's (Killer Instinct) in.",
      "Miss Fortune": "Your W (Cozy Campfire) range helps her position. Your R (Breath of Life) stops CC from cancelling her R (Bullet Time).",
      "Xayah": "Your R (Breath of Life) cleanse and peel (Q) are perfect for her.",
      "Aphelios": "Your W (Cozy Campfire) range and R (Breath of Life) cleanse are god-tier for him.",
      "Tristana": "Your W (Cozy Campfire) range and R (Breath of Life) cleanse make her all-in (W) very safe.",
      "Sivir": "Your W (Cozy Campfire) range makes her W (Ricochet) poke even stronger.",
      "Lucian": "Your W (Cozy Campfire) range allows him to dash (E) in, trade, and get out safely.",
      "Samira": "Your R (Breath of Life) cleanses CC, which can't be cleansed by her W (Blade Whirl).",
      "Vayne": "Your W (Cozy Campfire) range and R (Breath of Life) cleanse are perfect for her.",
      "Draven": "Your W (Cozy Campfire) range helps him catch axes. Your R (Breath of Life) is great peel.",
      "Varus": "Your W (Cozy Campfire) range is amazing for his On-Hit build. Your R (Breath of Life) is great peel.",
      "Zeri": "Your W (Cozy Campfire) range and R (Breath of Life) cleanse are perfect for her.",
      "Nilah": "Her passive (Joy Unending) amplifies your W (Cozy Campfire) heal/shield. Your R (Breath of Life) is great for her all-in.",
      "Smolder": "His W (Cozy Campfire) gives him the attack range to stack safely. Your R (Breath of Life) cleanses CC.",
      "Twitch": "Your W (Cozy Campfire) range on his R (Spray and Pray) is massive. Your R (Breath of Life) is great peel.",
      "Kog'Maw": "His W (Cozy Campfire) gives him even more range. His R (Breath of Life) cleanses CC. A perfect support.",
      "Kalista": "Your W (Cozy Campfire) range makes her kiting (Passive) even stronger.",
      "Senna": "Your W (Cozy Campfire) gives her even more range to stack souls.",
      "Seraphine": "Your W (Cozy Campfire) range helps her poke. Your R (Breath of Life) is great peel.",
      "Veigar": "Your W (Cozy Campfire) range helps him stack Q (Baleful Strike). Your R (Breath of Life) is great peel.",
      "Ziggs": "Your W (Cozy Campfire) range helps him poke. Your R (Breath of Life) is great peel.",
      "Karthus": "Your R (Breath of Life) is great peel. Your W (Cozy Campfire) helps him land Q (Lay Waste).",
      "Swain": "Your R (Breath of Life) is great peel. Your W (Cozy Campfire) helps him land E (Nevermove).",
      "Heimerdinger": "Your R (Breath of Life) is great peel. Your W (Cozy Campfire) helps him poke."
    }
  },
  "Yuumi": {
    synergy: {
      "Ashe": "You provide the speed (E) she needs to kite. Your R (Final Chapter) into her R (Arrow) is a long CC chain.",
      "Caitlyn": "Your R (Final Chapter) root is a free W (Trap) for her.",
      "Jinx": "You help her survive laning phase. Your E (Zoomies) speed on her passive (Get Excited!) is insane.",
      "Ezreal": "You are untargetable, and he is very safe (E). A very safe, but low-kill-pressure lane.",
      "Kai'Sa": "Your E (Zoomies) and R (Final Chapter) are great for her R (Killer Instinct) all-in.",
      "Miss Fortune": "Your R (Final Chapter) root is a good setup for her R (Bullet Time).",
      "Xayah": "Your R (Final Chapter) root holds them for her E (Bladecaller) root.",
      "Aphelios": "You help him survive laning phase. Your E (Zoomies) and R (Final Chapter) are great peel.",
      "Tristana": "Your E (Zoomies) and R (Final Chapter) are great for her W (Rocket Jump) all-in.",
      "Sivir": "Your E (Zoomies) speed on her R (On The Hunt) is very fast.",
      "Lucian": "Your Q (Prowling Projectile) slow helps him land his all-in.",
      "Samira": "Your R (Final Chapter) root is a good setup for her all-in.",
      "Vayne": "You help her survive laning phase. Your E (Zoomies) speed is great for her R (Final Hour) kiting.",
      "Draven": "Your E (Zoomies) speed helps him catch axes. Your R (Final Chapter) is a free kill.",
      "Varus": "Your R (Final Chapter) root into his R (Chain of Corruption) is a devastating CC chain.",
      "Zeri": "Makes her an unkillable, uncatchable machine. Your E (Zoomies) and R (Final Chapter) combo perfectly with her kit.",
      "Nilah": "Her passive (Joy Unending) amplifies your E (Zoomies) heal/shield. Your R (Final Chapter) sets up her R (Apotheosis).",
      "Smolder": "You help him survive laning phase. Your E (Zoomies) and R (Final Chapter) are great peel.",
      "Twitch": "Makes you a stealth bomber. Emerge from stealth (Q) with Yuumi's R (Final Chapter) for a devastating engage.",
      "Kog'Maw": "You help him survive laning phase. Your E (Zoomies) and R (Final Chapter) are great peel.",
      "Kalista": "Her R (Fate's Call) on you is... interesting. You can R (Final Chapter) from it.",
      "Senna": "Your Q (Prowling Projectile) poke and her Q (Piercing Darkness) poke are very strong.",
      "Seraphine": "A very safe, high-sustain poke lane. Your R (Final Chapter) sets up her R (Encore).",
      "Veigar": "You help him survive laning phase. Your R (Final Chapter) root is a free E (Event Horizon) stun.",
      "Ziggs": "A very safe, high-poke lane. Your R (Final Chapter) root sets up his R (Mega Inferno Bomb).",
      "Karthus": "Your R (Final Chapter) root holds them in his E (Defile).",
      "Swain": "Your R (Final Chapter) root is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your R (Final Chapter) root holds them in his turret (Q) nest."
    }
  },
  "Renata Glasc": {
    synergy: {
      "Ashe": "Your R (Hostile Takeover) is a great setup for her R (Arrow). Your W (Loyalty Program) is a free revive.",
      "Caitlyn": "Your R (Hostile Takeover) is a free W (Trap) for her. Your W (Loyalty Program) is a free revive.",
      "Jinx": "Your W (Loyalty Program) revive can guarantee she gets a reset (Passive).",
      "Ezreal": "Your Q (Loyalty Program) is good peel. Your W (Loyalty Program) is a free revive.",
      "Kai'Sa": "Your W (Loyalty Program) revive on her R (Killer Instinct) all-in is very strong.",
      "Miss Fortune": "Your R (Hostile Takeover) into her R (Bullet Time) is a wombo-combo.",
      "Xayah": "Your R (Hostile Takeover) holds them for her E (Bladecaller) root. Your W (Loyalty Program) is a free revive.",
      "Aphelios": "Your W (Loyalty Program) revive is god-tier for him.",
      "Tristana": "Your W (Loyalty Program) revive on her W (Rocket Jump) all-in is very strong.",
      "Sivir": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) is great engage.",
      "Lucian": "Your W (Loyalty Program) revive on his all-in is very strong.",
      "Samira": "Your R (Hostile Takeover) is a great setup for her R (Inferno Trigger). Your W (Loyalty Program) revive is insane.",
      "Vayne": "Your W (Loyalty Program) revive is god-tier for her. Your R (Hostile Takeover) is great peel.",
      "Draven": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) is a free kill.",
      "Varus": "Your R (Hostile Takeover) into his R (Chain of Corruption) is a devastating CC chain.",
      "Zeri": "Your W (Loyalty Program) revive is god-tier for her. Your R (Hostile Takeover) is great engage.",
      "Nilah": "Your W (Loyalty Program) revive on her R (Apotheosis) all-in is very strong.",
      "Smolder": "Your W (Loyalty Program) revive is god-tier for him. Your R (Hostile Takeover) is great peel.",
      "Twitch": "Your W (Loyalty Program) revive on his R (Spray and Pray) all-in is very strong.",
      "Kog'Maw": "Your W (Loyalty Program) revive is god-tier for him. Your R (Hostile Takeover) is great peel.",
      "Kalista": "Your W (Loyalty Program) revive is great. Her R (Fate's Call) on you is a massive engage.",
      "Senna": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) sets up her W (Last Embrace).",
      "Seraphine": "Your R (Hostile Takeover) into her R (Encore) is a full-team CC chain.",
      "Veigar": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) is a free E (Event Horizon) stun.",
      "Ziggs": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) is a free R (Mega Inferno Bomb).",
      "Karthus": "Your W (Loyalty Program) revive is god-tier for him. Your R (Hostile Takeover) holds them in his E (Defile).",
      "Swain": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) is a free E (Nevermove) root.",
      "Heimerdinger": "Your W (Loyalty Program) revive is great. Your R (Hostile Takeover) holds them in his turrets (Q)."
    }
  },
  
  // ===========================================================================
  // III. POKE SUPPORTS
  // ===========================================================================
  "Lux": {
    synergy: {
      "Ashe": "Your Q (Light Binding) into her R (Arrow) is a perma-CC. Your E (Lucent Singularity) slow guarantees her W (Volley).",
      "Caitlyn": "Her W (Yordle Snap-Trap) root setup from your Q (Light Binding) is a classic, lethal combo.",
      "Jinx": "Your Q (Light Binding) root sets up her E (Chompers) for a long CC chain.",
      "Ezreal": "Your combined Q (Light Binding) and E (Lucent Singularity) poke can force the enemy out of lane before level 6.",
      "Kai'Sa": "Your Q (Light Binding) is a free plasma (Passive) stack for her.",
      "Miss Fortune": "Your Q (Light Binging) or E (Lucent Singularity) slow is a perfect setup for her R (Bullet Time).",
      "Xayah": "Your Q (Light Binding) root holds them for her E (Bladecaller) root.",
      "Aphelios": "Your Q (Light Binding) root with his Purple (Gravitum) root is a 3-second CC.",
      "Tristana": "Your Q (Light Binding) root is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your E (Lucent Singularity) slow helps her land Q (Boomerang Blade).",
      "Lucian": "Your Q (Light Binding) root is a free all-in for him.",
      "Samira": "Your Q (Light Binding) root is a good setup for her all-in.",
      "Vayne": "Your Q (Light Binding) root can set up her E (Condemn) stun.",
      "Draven": "Your Q (Light Binding) root is a free kill for him.",
      "Varus": "Your Q (Light Binding) root into his R (Chain of Corruption) is a deadly CC chain.",
      "Zeri": "Your Q (Light Binding) root is one of the few ways to lock her down.",
      "Nilah": "Your Q (Light Binding) root is a good setup for her all-in.",
      "Smolder": "Your Q (Light Binding) is good peel. Your E (Lucent Singularity) provides vision for him.",
      "Twitch": "Your Q (Light Binding) root is a great setup for his all-in.",
      "Kog'Maw": "Your Q (Light Binding) is great peel. Your W (Prismatic Barrier) shield is very useful.",
      "Kalista": "Your Q (Light Binding) root is a good setup for her E (Rend) stack.",
      "Senna": "Your Q (Light Binding) root sets up her W (Last Embrace) root. A very long CC chain.",
      "Seraphine": "Your E (Lucent Singularity) slow guarantees her E (Beat Drop) root.",
      "Veigar": "Your Q (Light Binding) root is a free E (Event Horizon) stun. A classic 'cage of death' lane.",
      "Ziggs": "Your Q (Light Binding) root is a free full combo (E-W-Q) for him.",
      "Karthus": "Your Q (Light Binding) root holds them in his E (Defile) and guarantees Q (Lay Waste).",
      "Swain": "Your Q (Light Binding) root is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your Q (Light Binding) root holds them in his turrets (Q) and sets up his E (Grenade) stun."
    }
  },
  "Morgana": {
    synergy: {
      "Ashe": "Your Q (Dark Binding) into her R (Arrow) is a 5-second CC. Your E (Black Shield) stops divers.",
      "Caitlyn": "Your Q (Dark Binding) root (3 seconds) lasts long enough for her to place a W (Yordle Snap-Trap) underneath for a perma-root.",
      "Jinx": "Your Q (Dark Binding) root sets up her E (Chompers) perfectly.",
      "Ezreal": "Your E (Black Shield) on him allows him to E (Arcane Shift) in aggressively.",
      "Kai'Sa": "Your Q (Dark Binding) is a free plasma (Passive) stack. Your E (Black Shield) on her R (Killer Instinct) engage is very strong.",
      "Miss Fortune": "Your Q (Dark Binding) root or R (Soul Shackles) stun is a perfect setup for her R (Bullet Time).",
      "Xayah": "Your Q (Dark Binding) root holds them for her E (Bladecaller) root.",
      "Aphelios": "Your E (Black Shield) is critical for keeping him safe from CC (e.g., Thresh hook).",
      "Tristana": "Your E (Black Shield) on her W (Rocket Jump) engage makes her unstoppable.",
      "Sivir": "Your E (Black Shield) guarantees her E (Spell Shield) won't be broken, giving her free mana and safety.",
      "Lucian": "Your Q (Dark Binding) root is a free all-in. Your E (Black Shield) lets him dash (E) in safely.",
      "Samira": "Your E (Black Shield) prevents her R (Inferno Trigger) from being cancelled by CC.",
      "Vayne": "Your E (Black Shield) is the peel she needs to survive. Your Q (Dark Binding) sets up her E (Condemn).",
      "Draven": "Your Q (Dark Binding) is a free kill. Your E (Black Shield) makes him immune to CC while catching axes.",
      "Varus": "Your Q (Dark Binding) root into his R (Chain of Corruption) is a deadly CC chain.",
      "Zeri": "Your E (Black Shield) makes her immune to slows, which is a hard counter to her kit. (Anti-synergy).",
      "Nilah": "Your E (Black Shield) on her R (Apotheosis) engage is very strong.",
      "Smolder": "Your E (Black Shield) is perfect peel to help him stack safely.",
      "Twitch": "Your E (Black Shield) on him during his R (Spray and Pray) is very strong.",
      "Kog'Maw": "Your E (Black Shield) is the peel he needs to survive.",
      "Kalista": "Your E (Black Shield) allows her to kite (Passive) freely without fear of CC.",
      "Senna": "Your Q (Dark Binding) root sets up her W (Last Embrace) root. Your E (Black Shield) keeps her safe.",
      "Seraphine": "Your Q (Dark Binding) root sets up her full combo. Your E (Black Shield) keeps her safe.",
      "Veigar": "Your Q (Dark Binding) root is a free E (Event Horizon) stun. Your E (Black Shield) keeps him safe.",
      "Ziggs": "Your Q (Dark Binding) root sets up his full combo. Your E (Black Shield) keeps him safe.",
      "Karthus": "Your Q (Dark Binding) root holds them in his E (Defile). Your E (Black Shield) keeps him safe.",
      "Swain": "Your Q (Dark Cinding) root is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your Q (Dark Binding) root holds them in his turrets (Q). Your E (Black Shield) protects him."
    }
  },
  "Zyra": {
    synergy: {
      "Ashe": "Your E (Grasping Roots) and R (Stranglethorns) are a perfect setup for her R (Arrow).",
      "Caitlyn": "Your E (Grasping Roots) root is a free W (Trap) for her.",
      "Jinx": "Your E (Grasping Roots) root sets up her E (Chompers).",
      "Ezreal": "Your E (Grasping Roots) root guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your E (Grasping Roots) root is a free plasma (Passive) stack.",
      "Miss Fortune": "Your E (Grasping Roots) and R (Stranglethorns) are a perfect setup for her R (Bullet Time).",
      "Xayah": "Your E (Grasping Roots) and R (Stranglethorns) hold them for her E (Bladecaller) root.",
      "Aphelios": "Your E (Grasping Roots) and R (Stranglethorns) are the peel he needs.",
      "Tristana": "Your E (Grasping Roots) root is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your E (Grasping Roots) root helps her land Q (Boomerang Blade).",
      "Lucian": "Your E (Grasping Roots) root is a free all-in for him.",
      "Samira": "Your R (Stranglethorns) knock-up stacks her passive (Daredevil Impulse).",
      "Vayne": "Your E (Grasping Roots) root can set up her E (Condemn) stun.",
      "Draven": "Your E (Grasping Roots) root is a free kill for him.",
      "Varus": "Your E (Grasping Roots) and R (Stranglethorns) set up his R (Chain of Corruption).",
      "Zeri": "Your E (Grasping Roots) and R (Stranglethorns) are one of the few ways to lock her down.",
      "Nilah": "Your E (Grasping Roots) and R (Stranglethorns) are a great setup for her all-in.",
      "Smolder": "Your E (Grasping Roots) and R (Stranglethorns) are perfect peel for him.",
      "Twitch": "Your E (Grasping Roots) and R (Stranglethorns) are a great setup for his all-in.",
      "Kog'Maw": "Your E (Grasping Roots) and R (Stranglethorns) are perfect peel for him.",
      "Kalista": "Your E (Grasping Roots) root is a good setup for her E (Rend) stack.",
      "Senna": "Your E (Grasping Roots) root sets up her W (Last Embrace) root.",
      "Seraphine": "Your E (Grasping Roots) root sets up her E (Beat Drop) stun.",
      "Veigar": "Your E (Grasping Roots) root is a free E (Event Horizon) stun.",
      "Ziggs": "Your E (Grasping Roots) root sets up his full combo.",
      "Karthus": "Your E (Grasping Roots) and R (Stranglethorns) hold them in his E (Defile).",
      "Swain": "Your E (Grasping Roots) root is a free E (Nevermove) root for him.",
      "Heimerdinger": "The ultimate 'zone' lane. You control all bushes with turrets (Q) and plants."
    }
  },
  "Brand": {
    synergy: {
      "Ashe": "Your Q (Sear) stun is a free R (Arrow) for her.",
      "Caitlyn": "Your Q (Sear) stun is a free W (Trap) for her.",
      "Jinx": "Your Q (Sear) stun sets up her E (Chompers).",
      "Ezreal": "Your Q (Sear) stun guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your Q (Sear) stun is a free plasma (Passive) stack.",
      "Miss Fortune": "Your Q (Sear) stun and R (Pyroclasm) are a perfect setup for her R (Bullet Time).",
      "Xayah": "Your Q (Sear) stun holds them for her E (Bladecaller) root.",
      "Aphelios": "Your Q (Sear) stun is the peel he needs.",
      "Tristana": "Your Q (Sear) stun is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your Q (Sear) stun helps her land Q (Boomerang Blade).",
      "Lucian": "Your Q (Sear) stun is a free all-in for him.",
      "Samira": "Your Q (Sear) stun is a good setup for her all-in.",
      "Vayne": "Your Q (Sear) stun can set up her E (Condemn) stun.",
      "Draven": "Your Q (Sear) stun is a free kill for him.",
      "Varus": "Your Q (Sear) stun sets up his R (Chain of Corruption).",
      "Zeri": "Your Q (Sear) stun is one of the few ways to lock her down.",
      "Nilah": "Your Q (Sear) stun is a good setup for her all-in.",
      "Smolder": "Your Q (Sear) stun is perfect peel for him.",
      "Twitch": "Your Q (Sear) stun is a great setup for his all-in.",
      "Kog'Maw": "Your Q (Sear) stun is perfect peel for him.",
      "Kalista": "Your Q (Sear) stun is a good setup for her E (Rend) stack.",
      "Senna": "Your Q (Sear) stun sets up her W (Last Embrace) root.",
      "Seraphine": "Your Q (Sear) stun sets up her E (Beat Drop) stun.",
      "Veigar": "Your Q (Sear) stun is a free E (Event Horizon) stun.",
      "Ziggs": "Your Q (Sear) stun sets up his full combo.",
      "Karthus": "Your Q (Sear) stun holds them in his E (Defile).",
      "Swain": "Your Q (Sear) stun is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your Q (Sear) stun holds them in his turrets (Q)."
    }
  },

  // ===========================================================================
  // IV. SPECIALIST / CATCHER SUPPORTS
  // ===========================================================================
  "Pyke": {
    synergy: {
      "Ashe": "Your Q (Bone Skewer) hook is a free R (Arrow) for her. Your R (Death From Below) execute shares gold.",
      "Caitlyn": "Your Q (Bone Skewer) hook is a free W (Trap) for her.",
      "Jinx": "Your Q (Bone Skewer) hook sets up her E (Chompers).",
      "Ezreal": "Your Q (Bone Skewer) hook guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your Q (Bone Skewer) hook is a free plasma (Passive) stack.",
      "Miss Fortune": "Your Q (Bone Skewer) hook and E (Phantom Undertow) stun are a perfect setup for her R (Bullet Time).",
      "Xayah": "Your Q (Bone Skewer) hook and E (Phantom Undertow) stun hold them for her E (Bladecaller) root.",
      "Aphelios": "Your Q (Bone Skewer) hook with his Purple (Gravitum) root is a long CC chain.",
      "Tristana": "Your Q (Bone Skewer) hook is a free E (Explosive Charge) stack for her.",
      "Sivir": "Anti-synergy. She will E (Spell Shield) your Q (Bone Skewer) hook for free mana.",
      "Lucian": "Your Q (Bone Skewer) hook is a free all-in for him.",
      "Samira": "Your Q (Bone Skewer) hook and E (Phantom Undertow) stun stack her passive (Daredevil Impulse).",
      "Vayne": "Your Q (Bone Skewer) hook can set up her E (Condemn) stun.",
      "Draven": "Your Q (Bone Skewer) hook is a free kill for him. All-in at level 2.",
      "Varus": "Your Q (Bone Skewer) hook sets up his R (Chain of Corruption).",
      "Zeri": "Your Q (Bone Skewer) hook is one of the few ways to lock her down.",
      "Nilah": "Your Q (Bone Skewer) hook pulls them in for her all-in.",
      "Smolder": "You provide peel with Q (Bone Skewer) and E (Phantom Undertow). But you want to roam, and he wants to farm. Mismatch.",
      "Twitch": "Your Q (Bone Skewer) hook and E (Phantom Undertow) stun are a great setup for his all-in.",
      "Kog'Maw": "You provide peel with Q (Bone Skewer) and E (Phantom Undertow).",
      "Kalista": "Your Q (Bone Skewer) hook is a good setup for her E (Rend) stack.",
      "Senna": "Your Q (Bone Skewer) hook sets up her W (Last Embrace) root.",
      "Seraphine": "Your Q (Bone Skewer) hook guarantees her E (Beat Drop) stun.",
      "Veigar": "Your Q (Bone Skewer) hook into his E (Event Horizon) is a free kill.",
      "Ziggs": "Your Q (Bone Skewer) hook pulls them into his E (Hexplosive Minefield).",
      "Karthus": "Your Q (Bone Skewer) hook pulls them into his E (Defile).",
      "Swain": "Your Q (Bone Skewer) hook into his E (Nevermove) is a deadly double-pull combo.",
      "Heimerdinger": "Your Q (Bone Skewer) hook pulls them into his turret (Q) nest."
    }
  },
  "Bard": {
    synergy: {
      "Ashe": "Your Q (Cosmic Binding) stun is a free R (Arrow) for her. Your R (Tempered Fate) is a long-range setup.",
      "Caitlyn": "Your Q (Cosmic Binding) stun is a free W (Trap) for her. Your R (Tempered Fate) is a long-range setup.",
      "Jinx": "Your Q (Cosmic Binding) stun sets up her E (Chompers).",
      "Ezreal": "Your Q (Cosmic Binding) stun guarantees his full W-Q (Essence Flux-Mystic Shot) combo.",
      "Kai'Sa": "Your Q (Cosmic Binding) stun is a free plasma (Passive) stack.",
      "Miss Fortune": "Your R (Tempered Fate) into her R (Bullet Time) is a classic wombo-combo (if timed correctly).",
      "Xayah": "Your Q (Cosmic Binding) stun holds them for her E (Bladecaller) root.",
      "Aphelios": "Your Q (Cosmic Binding) stun is the peel he needs. Your R (Tempered Fate) can save him.",
      "Tristana": "Your Q (Cosmic Binding) stun is a free E (Explosive Charge) stack for her.",
      "Sivir": "Your Q (Cosmic Binding) stun helps her land Q (Boomerang Blade).",
      "Lucian": "Your Q (Cosmic Binding) stun is a free all-in for him.",
      "Samira": "Your Q (Cosmic Binding) stun is a good setup for her all-in.",
      "Vayne": "Your Q (Cosmic Binding) stun can set up her E (Condemn) stun.",
      "Draven": "Your Q (Cosmic Binding) stun is a free kill for him.",
      "Varus": "Your R (Tempered Fate) into his R (Chain of Corruption) is a devastating CC chain.",
      "Zeri": "Your Q (Cosmic Binding) stun is one of the few ways to lock her down.",
      "Nilah": "Your Q (Cosmic Binding) stun is a good setup for her all-in.",
      "Smolder": "Your W (Caretaker's Shrine) health packs help him stack safely. Your E (Magical Journey) is a good escape.",
      "Twitch": "Your R (Tempered Fate) is a great setup for his R (Spray and Pray).",
      "Kog'Maw": "Your Q (Cosmic Binding) stun and R (Tempered Fate) are perfect peel for him.",
      "Kalista": "Your Q (Cosmic Binding) stun is a good setup for her E (Rend) stack.",
      "Senna": "Your Q (Cosmic Binding) stun sets up her W (Last Embrace) root.",
      "Seraphine": "Your R (Tempered Fate) is a perfect setup for her R (Encore).",
      "Veigar": "Your Q (Cosmic Binding) stun or R (Tempered Fate) is a free E (Event Horizon) stun.",
      "Ziggs": "Your Q (Cosmic Binding) stun or R (Tempered Fate) sets up his R (Mega Inferno Bomb).",
      "Karthus": "Your Q (Cosmic Binding) stun or R (Tempered Fate) holds them in his E (Defile).",
      "Swain": "Your Q (Cosmic Binding) stun is a free E (Nevermove) root for him.",
      "Heimerdinger": "Your Q (Cosmic Binding) stun or R (Tempered Fate) holds them in his turret (Q) nest."
    }
  }
};
